### ISSUE TITLE
起timer的线程和执行定时器函数的线程不一样

### ISSUE THREAD

**Issue by boycehe** [CNKCQ/GlobalTimer#9]
调用- (void)scheduledWith: (NSString  * _Nonnull )identifirer timeInterval: (NSTimeInterval)interval repeat:(BOOL)repeat block:(GTBlock _Nonnull )block userinfo:(NSDictionary * _Nullable)userinfo
等方法时候 
执行block的线程并不是起timer的线程

**Comment by CNKCQ** [comment]
避免相同线程阻塞，暂不支持
